name: flutter_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # for routing => https://pub.dev/packages/auto_route
  auto_route: ^8.1.3

  # for caching images => https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.3.1

  # for network requests => https://pub.dev/packages/dio
  dio: ^5.4.3+1

  # for equality => https://pub.dev/packages/equatable
  equatable: ^2.0.5

  # for theme => https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^7.3.1

  flutter:
    sdk: flutter

  # for state management => https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.5

  # for environments => https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0

  # for generating assets code => https://pub.dev/packages/flutter_gen
  flutter_gen: ^5.5.0+1

  # for useful hooks => https://pub.dev/packages/flutter_hooks
  flutter_hooks: ^0.20.5

  # for responsibility => https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3

  # for svg => https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1

  # for functional programming => https://pub.dev/packages/fpdart
  fpdart: ^1.1.0

  # for dependency injection => https://pub.dev/packages/get_it
  get_it: ^7.7.0

  # for theme or locale management => https://pub.dev/packages/hydrated_bloc
  hydrated_bloc: ^9.1.5

  intl: ^0.19.0

  # for local data source
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # for creating api models => https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  # for app data directories
  path_provider: ^2.1.3

  # a dio interceptor for developer => https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.3.1

  # for shimmer effect => https://pub.dev/packages/shimmer
  shimmer: ^3.0.0

  # for url launcher => https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.0

dev_dependencies:
  # auto_route generator => https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^8.0.0

  # for testing bloc => https://pub.dev/packages/bloc_test
  bloc_test: ^9.1.7

  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  # for local data source 
  isar_generator: ^3.1.0+1

  # for creating api models => https://pub.dev/packages/json_serializable
  json_serializable: ^6.8.0

  # for testing => https://pub.dev/packages/mockito
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/icons/

flutter_gen:
  output: lib/src/config/gen/
  inputs:
  - assets/icons/

  integrations:
    flutter_svg: true
